### ISSUE TITLE
Contacts example crashes on "Sign In" button click

### ISSUE THREAD

**Issue by tgbarker** [Rainbow-CPaaS/Rainbow-Android-SDK-Samples#2]
Hi,

In the contacts example, if I enter a correct user name and password or even leave the text fields blank, when one clicks on the sign in button the example apk crashes here :

06-19 10:48:29.867 20066-20066/com.contacts E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.contacts, PID: 20066
    android.app.RemoteServiceException: Bad notification posted from package com.contacts: Couldn't create icon: StatusBarIcon(pkg=com.contactsuser=0 id=0x7f07005c level=0 visible=true num=0 )
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1480)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5343)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700)

I also updated to     implementation 'com.ale:rainbowsdk:1.42.0' as the project targets an old lib 1.40.0

This didn't help either.

**Comment by jon67400** [comment]
Strange. Do you remove appId and appSecret in MyApp class?

**Comment by letrongh** [comment]
Hello

Is it solved?
